### ISSUE TITLE
Install Configurator

### ISSUE THREAD

**Issue by XO2-Brocker** [e154/smart-home-configurator#111]
I'm having trouble installing the configurator.

1.) ./bin/project.sh --init
The script is missing: "static_source/private" and bower json-Files.

2.)
The "./cd static_source && gulp" command
does not work.

3)
Start smart-home-configurator

 ___                _     _  _
/ __|_ __  __ _ _ _| |_  | || |___ _ __  ___
\__ \ '  \/ _' | '_|  _| | __ / _ \ '  \/ -_)
|___/_|_|_\__,_|_|  \__| |_||_\___/_|_|_\___|

INFO    client                  client/client.go:20 >   grpc client connects to server :3000
INFO    api                     api/server.go:56 >      debug enabled
panic: html/template: pattern matches no files: `build/*/**.html`

goroutine 1 [running]:
html/template.Must(...)
        /usr/lib/go/src/html/template/template.go:368
github.com/e154/smart-home-configurator/api.(*Server).Start(0xc000330840)
        /mnt/SSD02/smart-home-configurator/api/server.go:76 +0x7d5
github.com/e154/smart-home-configurator/cmd/commands.glob..func1.1(0x0?, 0x0?)
        /mnt/SSD02/smart-home-configurator/cmd/commands/server.go:47 +0x1c
reflect.Value.call({0xa72b00?, 0xbd4500?, 0xc9c180?}, {0xb7e209, 0x4}, {0xc000332de0, 0x2, 0x0?})
        /usr/lib/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0xa72b00?, 0xbd4500?, 0x2?}, {0xc000332de0?, 0xc0000a0cb0?, 0xc000332de0?})
        /usr/lib/go/src/reflect/value.go:368 +0xbc
go.uber.org/dig.defaultInvoker({0xa72b00?, 0xbd4500?, 0xc0000a0ca0?}, {0xc000332de0?, 0x2?, 0xc97118?})
        /mnt/SSD02/smart-home-configurator/vendor/go.uber.org/dig/dig.go:355 +0x28
go.uber.org/dig.(*Container).Invoke(0xc0000b6730, {0xa72b00?, 0xbd4500}, {0xf3b558?, 0x1098ce0?, 0xc0002c8c30?})
        /mnt/SSD02/smart-home-configurator/vendor/go.uber.org/dig/dig.go:510 +0x3a5
go.uber.org/fx.(*App).executeInvoke(0xc00032a000, {{0xa72b00, 0xbd4500}, {0xc0002f7200, 0x6, 0x7}})
        /mnt/SSD02/smart-home-configurator/vendor/go.uber.org/fx/app.go:976 +0x39f
go.uber.org/fx.(*App).executeInvokes(...)
        /mnt/SSD02/smart-home-configurator/vendor/go.uber.org/fx/app.go:941
go.uber.org/fx.New({0xc00028fca8, 0x3, 0xe?})
        /mnt/SSD02/smart-home-configurator/vendor/go.uber.org/fx/app.go:600 +0xadb
github.com/e154/smart-home-configurator/cmd/container.BuildContainer({0xc918a8, 0xc0002654d0})
        /mnt/SSD02/smart-home-configurator/cmd/container/container.go:34 +0x1ce
github.com/e154/smart-home-configurator/cmd/commands.glob..func1(0x10f43c0?, {0xb7e5cd?, 0x0?, 0x0?})
        /mnt/SSD02/smart-home-configurator/cmd/commands/server.go:43 +0x125
github.com/spf13/cobra.(*Command).execute(0x10f43c0, {0xc000036220, 0x0, 0x0})
        /mnt/SSD02/smart-home-configurator/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x10f43c0)
        /mnt/SSD02/smart-home-configurator/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /mnt/SSD02/smart-home-configurator/vendor/github.com/spf13/cobra/command.go:902
main.main()
        /mnt/SSD02/smart-home-configurator/main.go:6 +0x25

What could be the problem?
Thanks!

P.S: The server runs without problems

**Comment by e154** [comment]
Hey! your "build" directory is missing or empty
it should contain static files for frontend
please try  `make build_public`
this command will create all needed files in "build" directory

**Comment by XO2-Brocker** [comment]
Thank you for your response.

Unfortunately there is still a problem.

I get the following message:
(Is it possible that the node version is wrong? I am using Node 16.x)

⠙  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
⠦  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
⠼  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
⠦  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
⠏  Building for production...node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
make: *** [Makefile:72: build_public] Fehler 134

**Comment by XO2-Brocker** [comment]
I found the problem:

Node-version 14 is required because Fibers (part of vue-cli-service) does not work with node version 16.

look:
Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial.


I downgraded it and now it works. One more question.

The following login data is suggested:
User: admin@e154.ru
Passport: admin

I can not login. What could be the problem?

(thanks for the great project)

**Comment by e154** [comment]
in what order and what commands do you execute?

please check that
1) the public part was assembled without errors
2) copy config.dev.json config to config.json

```
./smart-home
...
[Fx] RUNNING
Serving GRPC server at :3000
Serving WS server at :3003
Serving PROMETHEUS server at :3002
Serving HTTP server at :3001
```


```
./smart-home-configurator
grpc client connects to server :3000
debug enabled
set proxy http requests to http://localhost:3001
server started at :8080
[Fx] RUNNING
```

if the instruction did not help to enter the console, please give step by step your actions in order to repeat with me

**Comment by e154** [comment]
for quick help with questions, write to telegram https://t.me/SmartHomGo
